import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Hero'
import ProjectPreview from '../components/ProjectPreview'
// import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div id="home" className="antialiased text-secondary-color font-league-spartan leading-relaxed">
            <Head>
                <title>Irfanul Islam</title>
                {/* <meta name="description" content="Generated by create next app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className="mx-[6%] md:mx-[18%]">
                <Hero />
                <About />
                <ProjectPreview />
                <Contact />
                <Footer />
            </main>
        </div>
    )
}

